# Generated by Django 4.0.3 on 2022-05-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='creates_on',
            field=models.DateTimeField(),
        ),
    ]
