# Generated by Django 4.0.3 on 2022-04-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('subject', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('min_pass_points', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, default='draft', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MakeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=64)),
                ('max_time', models.DurationField(blank=True, null=True)),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('difficulty_level', models.CharField(max_length=64)),
                ('exam_model', models.ManyToManyField(to='exam_app.makeexam')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=124)),
                ('index', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=124)),
                ('index', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
    ]
