# Generated by Django 4.0.3 on 2022-05-16 18:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('subject', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('min_pass_points', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, default='Draft', max_length=64)),
                ('has_sections', models.BooleanField(default=False)),
                ('multiple_attempts', models.BooleanField(default=False)),
                ('instructions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MakeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('question_type', models.CharField(max_length=64)),
                ('max_time', models.DurationField(null=True)),
                ('max_points', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(default='None', max_length=64, null=True)),
                ('evaluation_type', models.BooleanField(default=False)),
                ('exam', models.ManyToManyField(to='exam_app.makeexam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Yet To Take', max_length=64)),
                ('result_status', models.CharField(blank=True, max_length=64, null=True)),
                ('overall_points', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(default=None, null=True)),
                ('end_time', models.TimeField(default=None, null=True)),
                ('time_elapsed', models.DurationField(null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makeexam')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, default=0)),
                ('evaluation_status', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('time_elapsed', models.DurationField(null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('exam_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userexamdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('time_elapsed', models.DurationField(null=True)),
                ('exam_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userexamdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
                ('question_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userquestiondetails')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerTextInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_input', models.TextField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userquestiondetails')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_input', models.FileField(null=True, upload_to='')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userquestiondetails')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=124)),
                ('index', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
        migrations.CreateModel(
            name='MakeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=124)),
                ('sub_title', models.CharField(blank=True, max_length=124)),
                ('instructions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exam_app.makeexam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='makequestion',
            name='section',
            field=models.ManyToManyField(blank=True, default='', to='exam_app.makesection'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=124)),
                ('index', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
    ]
