# Generated by Django 4.0.3 on 2022-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerfileupload',
            name='answer_text_input',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
