# Generated by Django 4.0.3 on 2022-04-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeexam',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=64),
        ),
    ]
