# Generated by Django 4.0.3 on 2022-05-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_rename_exam_model_makequestion_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeexam',
            name='multiple_attempts',
            field=models.BooleanField(default=False),
        ),
    ]
