# Generated by Django 4.0.3 on 2022-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_makeexam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestiondetails',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
