# Generated by Django 4.0.3 on 2022-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_makequestion_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='max_points',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
