# Generated by Django 4.0.3 on 2022-04-21 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_app', '0003_userquestiondetails_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeexam',
            name='has_sections',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MakeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=124)),
                ('sub_title', models.CharField(blank=True, max_length=124)),
                ('instructions', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exam_app.makeexam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='makequestion',
            name='section',
            field=models.ManyToManyField(blank=True, default='', to='exam_app.makesection'),
        ),
    ]
