# Generated by Django 4.0.3 on 2022-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_makeexam_multiple_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeexam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='makeexam',
            name='time',
        ),
        migrations.AddField(
            model_name='makeexam',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
