# Generated by Django 4.0.3 on 2022-05-06 19:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_makeexam_date_remove_makeexam_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeexam',
            name='instructions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
