# Generated by Django 4.0.3 on 2022-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_makeexam_date_remove_makeexam_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestiondetails',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
