# Generated by Django 4.0.3 on 2022-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_makeexam_has_sections_makesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makesection',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
