# Generated by Django 4.0.3 on 2022-04-22 02:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_alter_makesection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makesection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='makesection',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
