# Generated by Django 4.0.3 on 2022-04-22 06:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_alter_makesection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
