# Generated by Django 4.0.3 on 2022-04-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_alter_makequestion_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('result_status', models.CharField(blank=True, max_length=64)),
                ('overall_points', models.IntegerField(blank=True)),
                ('time_elapsed', models.DurationField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makeexam')),
            ],
        ),
        migrations.AlterField(
            model_name='makequestion',
            name='difficulty_level',
            field=models.CharField(default='None', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='makequestion',
            name='max_points',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='makequestion',
            name='max_time',
            field=models.DurationField(null=True),
        ),
        migrations.CreateModel(
            name='UserQuestionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True)),
                ('evaluation_status', models.CharField(blank=True, max_length=64)),
                ('time_elapsed', models.DurationField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userexamdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerTextInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_input', models.TextField(blank=True)),
                ('index', models.IntegerField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userquestiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_input', models.TextField(blank=True)),
                ('index', models.IntegerField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userquestiondetails')),
            ],
        ),
    ]
