# Generated by Django 4.0.3 on 2022-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_userexamdetails_alter_makequestion_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerfileupload',
            name='answer_text_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswerfileupload',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswertextinput',
            name='answer_text_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswertextinput',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexamdetails',
            name='overall_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexamdetails',
            name='result_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='evaluation_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
