# Generated by Django 4.0.3 on 2022-04-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_alter_useranswerfileupload_answer_text_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestiondetails',
            old_name='exam',
            new_name='exam_details',
        ),
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('time_elapsed', models.DurationField(null=True)),
                ('exam_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.userexamdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.makequestion')),
            ],
        ),
    ]
