# Generated by Django 4.0.3 on 2022-04-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_remove_makesection_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='max_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userquestiondetails',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
