# Generated by Django 4.0.3 on 2022-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_alter_makequestion_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='section',
            field=models.ManyToManyField(blank=True, default='', related_query_name='questions', to='exam_app.makesection'),
        ),
    ]
