# Generated by Django 4.0.3 on 2022-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_alter_makequestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='section',
            field=models.ManyToManyField(blank=True, default='', to='exam_app.makesection'),
        ),
    ]
