# Generated by Django 4.0.3 on 2022-04-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_userquestiondetails_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestiondetails',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userquestiondetails',
            name='start_time',
        ),
    ]
