# Generated by Django 4.0.3 on 2022-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_alter_makequestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamdetails',
            name='status',
            field=models.CharField(default='Yet To Take', max_length=64),
        ),
    ]
