# Generated by Django 4.0.3 on 2022-04-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0014_remove_userquestiondetails_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresults',
            name='question_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
